spring.application.name=RestApiPractise
spring.mongodb.uri=mongodb+srv://balkhandehemantkumar1997_db_user:HS0fz62zTlh2RcE1@cluster0.myplct6.mongodb.net/?appName=Cluster0
spring.mongodb.database=Employeedb
spring.data.mongodb.auto-index-creation=true


